language: ruby

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

gemfile:
  - gemfiles/sinatra_14.gemfile

sudo: false

script: 'bundle exec rake spec'

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
