language: ruby

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - ruby-head
  - jruby-9.2.3.0
  - rbx-3

gemfile:
  - gemfiles/sinatra_20.gemfile
  - gemfiles/sinatra_14.gemfile

sudo: false

script: 'bundle exec rake test'

cache: bundler

matrix:
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/sinatra_14.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/sinatra_14.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sinatra_14.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.3.0
    - rvm: rbx-3
  fast_finish: true
