language: ruby

before_install: gem update bundler

rvm:
  - 2.2.6
  - 2.3.3
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

gemfile:
  - gemfiles/sinatra_14.gemfile
  - gemfiles/sinatra_20.gemfile

sudo: false

script: 'bundle exec rake test'

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true
