language: ruby

before_install: gem update bundler

rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - ruby-head
  - jruby-9.1.8.0
  - rbx-2

gemfile:
  - gemfiles/sinatra_14.gemfile
  - gemfiles/sinatra_20.gemfile

sudo: false

script: 'bundle exec rake test'

cache: bundler

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/sinatra_14.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sinatra_14.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.8.0
    - rvm: rbx-2
  fast_finish: true
